// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var actionsDemoForm, calendar, calendars, miniCalendar, option_sel;
    miniCalendar = $('div.mini-calendar').Calendar({
      miniMode: true
    });
    calendar = $('div.calendar').Calendar();
    calendars = $('div.mini-calendar, div.calendar').Calendar();
    actionsDemoForm = $('form[name="actions-demo"]');
    option_sel = "select[name=\"langs\"] option[value=\"" + (calendar.Calendar('option', 'lang')) + "\"]";
    $(option_sel, actionsDemoForm).prop('selected', 'selected');
    $('select[name="langs"]', actionsDemoForm).on('change', function(e) {
      e.preventDefault();
      return calendars.Calendar('option', 'lang', $(e.target).val());
    });
    option_sel = "select[name=\"viewType\"] option[value=\"" + (calendar.Calendar('option', 'viewType')) + "\"]";
    $(option_sel, actionsDemoForm).prop('selected', 'selected');
    $('select[name="viewType"]', actionsDemoForm).on('change', function(e) {
      e.preventDefault();
      return calendar.Calendar('option', 'viewType', parseInt($(e.target).val(), 10));
    });
    return miniCalendar.on('dayclicked', function(e, date) {
      return calendar.Calendar('changeViewTo', 1, date);
    });
  });

}).call(this);
