// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    $.fn.styledCheckbox = function() {
      return $(this).each(function() {
        var $this, styled;
        $this = $(this);
        $this.hide();
        styled = $('<span>').addClass('styled-checkbox');
        styled.html('&nbsp;');
        if ($this.is(':checked')) {
          styled.addClass('styled-checkbox-checked');
        }
        $this.after(styled);
        if ($this.prop('disabled')) {
          return;
        }
        return styled.on('click', function(e) {
          styled.toggleClass('styled-checkbox-checked');
          return $this.click();
        });
      });
    };
    return $('input[type="checkbox"]').styledCheckbox();
  });

}).call(this);
